Inse01 speciesprotocol
slambrechts/EJP-Soil pull request #2
Opened 2024-03-22 06:36 UTC by silkedebacker

INBO_0_10 vs Lucas aangepast: nu loopt alles normaal zonder error
INBO (INBO_0_10 + INBO_10_30) vs Lucas: toegevoegd

2024-03-22 10:39 UTC, silkedebacker commented
HTML:
[data_analyse_inse01_ejp.zip](https://github.com/slambrechts/EJP-Soil/files/14721314/data_analyse_inse01_ejp.zip)

2024-03-22 13:59 UTC, silkedebacker commented
Nieuwe HTML na toegoegen code LUCAS vs INBO(_0_10):

[data_analyse_inse01_ejp.zip](https://github.com/slambrechts/EJP-Soil/files/14723558/data_analyse_inse01_ejp.zip)

2024-03-27 16:33 UTC, slambrechts requested changes
@silkedebacker kan je de insecten `html `nog verwijderen uit je lokale `source/rmarkdown/` map en dan eens opnieuw commit push doen voor deze branch? Best dat je die altijd verplaatst naar de EJP-Soil gedeelde drive, en vervolgens verwijderd in je lokale Rstudio git project map, want anders gaat die mee online als je commit push doet.

Daarnaast zitten er in deze branch ook een paar aanpassingen van de `fungi `Rmd. Dat is waarschijnlijk per ongeluk? Ik post daar nog een oplossing voor nadat we de andere pull request, de pull request van de fungi zelf, kunnen sluiten en mergen

2024-03-28 08:50 UTC, slambrechts approved these changes

2024-03-28 08:56 UTC, slambrechts approved these changes

2024-03-28 08:58 UTC, merged