Fungi venn
slambrechts/EJP-Soil pull request #3
Opened 2024-03-22 07:28 UTC by silkedebacker

Venn diagrammen:

1. Code venn diagrammen aangepast zodat ook Diepenbeek_strooisel eruit
2. Niet meer manueel de locaties ingeven die in samples_to_remove zitten --> gaat nu automatisch

2024-03-22 10:13 UTC, silkedebacker commented
HTML
[data_analyse_inse01_ejp.zip](https://github.com/slambrechts/EJP-Soil/files/14720998/data_analyse_inse01_ejp.zip)

2024-03-22 16:59 UTC, silkedebacker commented
HTML:
[data_analyse_fungi_ejp.zip](https://github.com/slambrechts/EJP-Soil/files/14726019/data_analyse_fungi_ejp.zip)

2024-03-27 16:20 UTC, slambrechts reviewed
@silkedebacker ziet er allemaal goed uit! Ik vroeg mij alleen af waarom je eval=FALSE zet bij de verschillende read counts op het einde?

2024-03-27 16:20 UTC, slambrechts commented on source/rmarkdown/data_analyse_fungi_ejp.Rmd
> +```{r, eval= FALSE}
@silkedebacker waarom zet je `eval= FALSE ` bij de read counts van Phylum, Class, enz...?

2024-03-27 16:40 UTC, slambrechts requested changes
@silkedebacker kan je hier ook nog eens switchen naar deze branch, en dan voor de fungi de html files ook verwijderen uit je lokale source/rmarkdown/ map en dan eens opnieuw commit push doen voor deze branch? Dan kan ik deze branch mergen met de main en sluiten

2024-03-28 08:37 UTC, slambrechts approved these changes

2024-03-28 08:37 UTC, merged